### ISSUE TITLE
Baseline copyediting and correctness pass to update existing doc content

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#13]
## Issue Description

Currently, quite a few details and references in our documentation are out of date (e.g. to Mercurial support, Python(x, y), the non-IPython console, etc), and a number of grammar, style, and syntax problems exist. In this issue, I propose a baseline sweep through the existing stuff to clean up such easy to resolve items to ensure a baseline of textual quality for our initial public release of the new docs.

## Task List

* [x] Decide on conventions and create internal style guide (public version to be released as a separate issue/PR)
* [x] Initial cross-file changes
    * [x] Use consistent capitalization, marker characters, naming scheme, and structure for titles, headings and subheads, and add additional
    * [x] Rename "Related Plugins" section to "Related Components", make a L3 subhead, and cleanup/add additional links
    * [x] Harmonize all topic names to be bold and title case in first sentence
* [x] Index page
    * [x] Replace outdated content with heavily revised text from readme
    * [x] Make one sentance per line
    * [x] Re-organize and cleanup toctree
* [x] Baseline copyediting and corrections per file
    * [x] Remove/correct outdated information
    * [x] Copyedit text for better prose
    * [x] Harmonize line breaks to one per sentence to make both editing and reviewing changes much easier, and git much cleaner and more effective
    * [x] Add minimal necessary additional text/items to fill out at least one short section per doc
* [x] Add a few additional brief descriptions to bare links in overview
* [x] Fix numerous bad links and add https where possible
* [x] Harmonize formatting of elements/directives to conform to style guide 
  * [x] Admonitions
  * [x] Set two blank lines before all headings and overbar format for L2
  * [x] File names/paths
  * [x] Keyboard shortcuts
  * [x] GUI elements 
  * [x] Menu/preference selections
  * [x] Code blocks
