### ISSUE TITLE
Tasks before making an official release of the Spyder 4 docs

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#162]
After talking to @juanis2112 a couple of days ago, I came to the conclusion that we're really not helping our users by withholding a release of our in-development docs until all panes are documented.

Therefore, I propose to do an initial release right now with what we have. To make that a reality, I think we need to finish the following tasks:

- [x] Create an Overview page. @CAM-Gerlach and @juanis2112 are going to take care of this one.
- [x] Create Troubleshooting and FAQ pages. @juanis2112 will take care of this one.
- [x] Fix issue #155. I think @dalthviz is the only one that can help us to solve this one.
- [x] Fix issue #144. This one is almost ready.
- [x] Some images are still not centered (see for instance the Variable Explorer page).
- [x] Review, and update if needed, instructions to our Contributing guide about how to compile the new website.
- [ ] Update Readme after we publish the Spyder 4 docs in `docs.spyder-ide.org`.
- [x] Fix issue #165.
- [x] Fix issue #164.
- [x] Add selector to switch between Spyder 3 and 4 docs - #179 
- [x] Update screenshots of panes whose documentation has not been updated yet to use the dark theme. @juanis2112 is going to work on this one.
- [x] Make public "Working with Spyder" videos and add new videos about the Code Analysis and Profiler to that section. @juanis2112 will take care of it.

If you think there are more pending tasks, please feel free to edit this comment.

**Comment by CAM-Gerlach** [comment]
> Add instructions to our Contributing guide about how to compile the new website.

I thought @dalthviz updated it as nesesary (with some feedback by me) when he first committed the new theme?

**Comment by dalthviz** [comment]
Yep, I think that the contributing guide is updated :+1: although a double check to see if something is missing never is bad (I changed the item for `Review and update if needed ...` instead of `Add ..`).

**Comment by juanis2112** [comment]
I already had an idea for the Overview so I'll work on that with @CAM-Gerlach. 
I was also working on the missing sections that are on the cards so I'll try to finish that by the end of this week so instead of removing them we actually have something for those two sections.
I made some suggestions to @CAM-Gerlach about the contributing guide after @dalthviz fixes so we can give it a last review together (cause there are some typos too).
The issue with the images centered was fixed in a PR that I merged a couple of minutes ago which also included some general fixes regarding style bugs that @CAM-Gerlach found.
Finally, @CAM-Gerlach and I did a general review on the docs page and found some issues with margins and other stuff so I opened some issues in the theme's repo and tagged @dalthviz so he can take a look at them.

**Comment by ccordoba12** [comment]
Great to know @juanis2112! Please let us know if you need something else from @dalthviz or me.

**Comment by CAM-Gerlach** [comment]
As part of #158 I ended up doing a comprehensive update and improvement of the Contributing Guide too, since there were a bunch of things that needed updating, so hopefully that should be ready now but @dalthviz can check it one more time to make sure there's nothing missing on the build side (the instructions seem to work in our testing, with the exception of the typos @juanis2112 mentioned).

**Comment by CAM-Gerlach** [comment]
@juanis2112 We just need the screenshot for the readme so we can close this; lmk if you want me to do it or you want to. Thanks!
